FROM node:20.18.1-alpine

WORKDIR /app

# Install deps first (better cache)
COPY package*.json ./
RUN npm install

# Nodemon needs file system events
# this one makes sure nodemon uses polls, which is necessary with alpine
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]
