FROM node:20-alpine

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL


WORKDIR /app

# Only dependencies are baked into the image
COPY front/package*.json ./
RUN npm install

EXPOSE 5173

# Source code comes from bind mount
CMD ["npm", "run", "dev", "--", "--host"]
