FROM node:20-alpine

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL


WORKDIR /app

# Only dependencies are baked into the image
# the whole folder will be a bind mount so that we have hot reload -> ./containers/nginx_front/front-end:/app
COPY front-end/package*.json ./
RUN npm install

# EMILIE added for hot reloaded on windows
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=100

EXPOSE 5173

# Source code comes from bind mount
CMD ["npm", "run", "dev", "--", "--host"]
