FROM node:20.18.1-alpine

ARG VITE_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL


WORKDIR /app

# Only dependencies are baked into the image
COPY front-end/package*.json ./
RUN npm install

# EMILIE added for hot reloaded on windows
ENV CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_INTERVAL=100

EXPOSE 5173

# Source code comes from bind mount
CMD ["npm", "run", "dev", "--", "--host"]
