FROM node:20.19.6-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json ./
#
# Needed for bcrypt

#RUN npm install
#RUN npm update
#RUN npm rebuild
RUN npm ci

# Nodemon needs file system events
# this one makes sure nodemon uses polls, which is necessary with alpine
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]