FROM node:20.18.1-alpine

WORKDIR /app

COPY package*.json ./

# Needed for bcrypt
RUN apk add --no-cache python3 make g++

RUN npm install

# Nodemon needs file system events
# this one makes sure nodemon uses polls, which is necessary with alpine
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]